layout_spectrum: 0.09152882880365273
typography_spectrum: 0.9016581479409286
color:
  lightness: 0.07611957928885034
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
  saturation: 0.8688107111716256
  brandStrength: 0.6549906522196967
  rhythmicContrast: 0.7252007589982545
name: '#jaizenhom'
analytics:
  facebook: '233560110358876'
  google: UA-78405620-1
purpose: []
github: true
author:
  name: Jaizen Hom
  url: 'http://jaizenhom.com'
  email: jaizen.hom@gmail.com
cta:
  bucket: null
  version: null
  domain: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
content: []
navigation:
  - id: bfe81d0f-11ad-40f2-a290-bd1221f7744e
    name: About
    type: content
  - id: 5606e32d-ba27-45e6-ad69-5b88c63b2768
    name: Photos
    type: content
  - id: 51c6585a-189e-4fc0-af8e-1ec81cdd7dad
    name: Videos
    type: content
  - id: d7284858-78a7-4233-85c9-6b6b7bad4ded
    name: Contact
    type: content
content_rating:
  adult: false
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5a3f4fc2-bf54-46ec-b69f-73e07649de49.jpg
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/cee080e0-d29f-4a78-973e-c475f208c5a7.jpg
