typography_spectrum: 0.112766
color:
  saturation: 0.9810918583534658
  brandStrength: 0.6328616184182465
  rhythmicContrast: 0.009388403035700321
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  lightness: 0.5568422444630414
opengraph:
  image: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/cee080e0-d29f-4a78-973e-c475f208c5a7.jpg'
  type: null
  appId: null
layout_spectrum: 0.4438958871178329
analytics:
  twitter: null
  google: UA-78405620-1
  facebook: null
author:
  name: Jaizen Hom
  email: jaizen.hom@gmail.com
  url: 'http://jaizenhom.com'
name: jaizen hom
cta:
  bucket: null
  version: null
  domain: null
favicon: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/5a3f4fc2-bf54-46ec-b69f-73e07649de49.jpg'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Multi-National Man of Mystery... Author + Artist + Spokesmodel + Actor + Producer
purpose: []
