typography_spectrum: 0.112766
color:
  saturation: 0.5366714557167143
  brandStrength: 0.04598407866433263
  rhythmicContrast: 0.1090609561651945
  brandColors:
    - '#c9ab8f'
    - '#faf5e2'
    - '#1c130c'
    - '#443b02'
    - '#786e29'
  lightness: 0.01961908140219748
opengraph:
  image: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/cee080e0-d29f-4a78-973e-c475f208c5a7.jpg'
  type: null
  appId: null
layout_spectrum: 0.8767321782652289
analytics:
  twitter: null
  google: UA-78405620-1
  facebook: null
author:
  name: Jaizen Hom
  email: jaizen.hom@gmail.com
  url: 'http://jaizenhom.com'
name: jaizen hom
cta:
  bucket: null
  version: null
  domain: null
favicon: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/5a3f4fc2-bf54-46ec-b69f-73e07649de49.jpg'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Multi-National Man of Mystery... Author + Artist + Spokesmodel + Actor + Producer
purpose: []
