name: jaizen hom
favicon: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/5a3f4fc2-bf54-46ec-b69f-73e07649de49.jpg'
layout_spectrum: 0.9764073800761253
typography_spectrum: 0.112766
author:
  name: Jaizen Hom
  email: jaizen.hom@gmail.com
  url: 'http://jaizenhom.com'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Hom...Jaizen Hom... Multi-National Man of Mystery... Spokesmodel + SAG Actor + Super Producer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-78405620-1
  facebook: '233560110358876'
  twitter: null
opengraph:
  image: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/cee080e0-d29f-4a78-973e-c475f208c5a7.jpg'
  type: null
  appId: null
color:
  brandColors:
    - '#F7F2B2'
    - '#ADCF4F'
    - '#84815B'
    - '#4A1A2C'
    - '#8E3557'
  brandStrength: 0.4340793604496866
  lightness: 0.492533179698512
  saturation: 0.3125972237903625
  rhythmicContrast: 0.1611969880759716
purpose: []
